Create to do list page component - Vanilla.js
TBD54566975/tbd-examples pull request #384
Opened 2024-10-28 17:00 UTC by 29deepanshutyagi

issue #87

2024-10-29 10:45 UTC, blackgirlbytes requested changes

2024-10-29 10:45 UTC, blackgirlbytes commented on javascript/dwa-starter-vanillajs-vite/components.js
> +};
Hi @29deepanshutyagi ! Thanks for your contribution, but this PR seems to be missing a few things. For example, these methods have no logic in them..just a comment. We'll need to implement the logic for DWAs. The best place to look and understand how these work are in the DWA react vite project and in the DWA vue project.

Also the task and criteria say the following..I don't think I see that happening here:
Create a TaskItem.vanilla component for individual task display and actions

Create a TaskForm.vanilla component for adding/editing tasks

Implement TodoDwnRepository class for DWN operations:

listTasks()

createTask(task)

updateTask(task)

deleteTask(recordId)

findTaskRecord(recordId)

listTasksRecords()

2024-10-29 10:45 UTC, blackgirlbytes commented on javascript/shared-todo-starter/package.json
> +>>>>>>> ea24aa69758146611ddc3c604b61c014494d51f9
hmm i dont think you want those lines in the package.json. it looks like you have merge conflicts and duplicates

2024-10-29 17:30 UTC, blackgirlbytes commented on javascript/shared-todo-starter/package.json
> +>>>>>>> ea24aa69758146611ddc3c604b61c014494d51f9
Actually this file should have 0 changes as it's unrelated to your project

2024-10-29 17:30 UTC, blackgirlbytes commented on javascript/shared-todo/package.json
>      "sass-loader": "16.0.2",
this file should have 0 changes as it's unrelated to your project

2024-10-29 17:31 UTC, blackgirlbytes commented
oh no looks like this PR has a few changes in projects that aren't related to your own. Let's get that fixed up. If you need help, come to our office hours in Discord!

2024-10-30 17:20 UTC, taniashiba commented
@29deepanshutyagi - Hey there! Since Hacktoberfest officially closes tomorrow, we want to make sure all open PRs are resolved in full today in case of any issues. Please see comments above so you can get credit!

2024-10-31 19:47 UTC, blackgirlbytes commented
hey @29deepanshutyagi im going to close this one out because we only have a few hours left until hacktoberfest ends, and I haven't heard from you!

2024-10-31 19:47 UTC, closed without merging